setting:
  notification: True
  deadline: True
  routine: True
  finance: True
  deadline_day_time: 21:22
  deadline_hour_time: 23:00
  routine_time: 23:00
  finance_time: 20:00
  language: vi
  chat_id: 5415888127
  token: 8942508022:AAF5JMZjoPzpappMI_2wl_5H9Fm8Zfzwlbg
