setting:
  notification: True
  today_task: True
  daily_routine_report: True
  finance_alert: True
  schedule_for_tomorrow: False
  today_task_time: 11:46
  daily_routine_report_time: 12:17
  finance_report_time: 12:18
  schedule_for_tomorrow_time: 23:00
  timezone: Asia/Ho_Chi_Minh
  language: vi
  chat_id: 5415888127
  token: 8942508022:AAF5JMZjoPzpappMI_2wl_5H9Fm8Zfzwlbg
